# Data Wrangling - La cirugía de los datos

In [94]:
import pandas as pd
import timeit

In [95]:
data = pd.read_csv('./datasets/customer-churn-model/Customer Churn Model.txt')

In [96]:
data.head()

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False.
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False.
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False.
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False.
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False.

# Crear un subconjunto de datos

In [97]:
account_length = data["Account Length"]

In [98]:
account_length.head()

0    128
1    107
2    137
3     84
4     75
Name: Account Length, dtype: int64

In [99]:
type(account_length)

pandas.core.series.Series

In [100]:
subset = data[["Account Length", "Phone", "Eve Charge", "Day Calls"]]

In [101]:
subset.head()

   Account Length     Phone  Eve Charge  Day Calls
0             128  382-4657       16.78        110
1             107  371-7191       16.62        123
2             137  358-1921       10.30        114
3              84  375-9999        5.26         71
4              75  330-6626       12.61        113

In [102]:
type(subset)

pandas.core.frame.DataFrame

In [103]:
desired_columns = ["Account Length", "Phone", "Eve Charge", "Day Calls"]
subset =  data[desired_columns]
subset.head()

   Account Length     Phone  Eve Charge  Day Calls
0             128  382-4657       16.78        110
1             107  371-7191       16.62        123
2             137  358-1921       10.30        114
3              84  375-9999        5.26         71
4              75  330-6626       12.61        113

In [104]:
desired_columns = ["Account Length", "Wall Message", "Day Calls"]
all_columns_list = data.columns.tolist()

In [105]:
all_columns_list

['State',
 'Account Length',
 'Area Code',
 'Phone',
 "Int'l Plan",
 'VMail Plan',
 'VMail Message',
 'Day Mins',
 'Day Calls',
 'Day Charge',
 'Eve Mins',
 'Eve Calls',
 'Eve Charge',
 'Night Mins',
 'Night Calls',
 'Night Charge',
 'Intl Mins',
 'Intl Calls',
 'Intl Charge',
 'CustServ Calls',
 'Churn?']

In [106]:
%timeit sublist = list(set(all_columns_list) - set(desired_columns))

1.67 µs ± 139 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [107]:
%timeit sublist = [x for x in all_columns_list if x not in desired_columns]

2.11 µs ± 21.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [108]:
sublist = list(set(all_columns_list) - set(desired_columns))

In [109]:
sublist

['Area Code',
 "Int'l Plan",
 'Eve Charge',
 'VMail Message',
 'Intl Mins',
 'State',
 'Night Mins',
 'Day Mins',
 'Churn?',
 'Intl Calls',
 'CustServ Calls',
 'VMail Plan',
 'Night Calls',
 'Intl Charge',
 'Phone',
 'Day Charge',
 'Night Charge',
 'Eve Calls',
 'Eve Mins']

In [110]:
subset = data[sublist]

In [111]:
subset.head()

,Area Code,Int'l Plan,Eve Charge,VMail Message,Intl Mins,State,Night Mins,Day Mins,Churn?,Intl Calls,CustServ Calls,VMail Plan,Night Calls,Intl Charge,Phone,Day Charge,Night Charge,Eve Calls,Eve Mins
0,415,no,16.78,25,10.0,KS,244.7,265.1,False.,3,1,yes,91,2.70,382-4657,45.07,11.01,99,197.4
1,415,no,16.62,26,13.7,OH,254.4,161.6,False.,3,1,yes,103,3.70,371-7191,27.47,11.45,103,195.5
2,415,no,10.30,0,12.2,NJ,162.6,243.4,False.,5,0,no,104,3.29,358-1921,41.38,7.32,110,121.2
3,408,yes,5.26,0,6.6,OH,196.9,299.4,False.,7,2,no,89,1.78,375-9999,50.90,8.86,88,61.9
4,415,yes,12.61,0,10.1,OK,186.9,166.7,False.,3,3,no,121,2.73,330-6626,28.34,8.41,122,148.3

In [112]:
data[0:8]

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False.
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False.
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False.
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False.
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False.
5,AL,118,510,391-8027,yes,no,0,223.4,98,37.98,...,101,18.75,203.9,118,9.18,6.3,6,1.70,0,False.
6,MA,121,510,355-9993,no,yes,24,218.2,88,37.09,...,108,29.62,212.6,118,9.57,7.5,7,2.03,3,False.
7,MO,147,415,329-9001,yes,no,0,157.0,79,26.69,...,94,8.76,211.8,96,9.53,7.1,6,1.92,0,False.

In [113]:
data[10:35]

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
10,IN,65,415,329-6603,no,no,0,129.1,137,21.95,...,83,19.42,208.8,111,9.40,12.7,6,3.43,4,True.
11,RI,74,415,344-9403,no,no,0,187.7,127,31.91,...,148,13.89,196.0,94,8.82,9.1,5,2.46,0,False.
12,IA,168,408,363-1107,no,no,0,128.8,96,21.90,...,71,8.92,141.1,128,6.35,11.2,2,3.02,1,False.
13,MT,95,510,394-8006,no,no,0,156.6,88,26.62,...,75,21.05,192.3,115,8.65,12.3,5,3.32,3,False.
14,IA,62,415,366-9238,no,no,0,120.7,70,20.52,...,76,26.11,203.0,99,9.14,13.1,6,3.54,4,False.
15,NY,161,415,351-7269,no,no,0,332.9,67,56.59,...,97,27.01,160.6,128,7.23,5.4,9,1.46,4,True.
16,ID,85,408,350-8884,no,yes,27,196.4,139,33.39,...,90,23.88,89.3,75,4.02,13.8,4,3.73,1,False.
17,VT,93,510,386-2923,no,no,0,190.7,114,32.42,...,111,18.55,129.6,121,5.83,8.1,3,2.19,3,False.
18,VA,76,510,356-2992,no,yes,33,189.7,66,32.25,...,65,18.09,165.7,108,7.46,10.0,5,2.70,1,False.
19,TX,73,415,373-2782,no,no,0,224.4,90,38.15,...,88,13.56,192.8,74,8.68,13.0,2,3.51,1,False.
20,FL,147,415,396-5800,no,no,0,155.1,117,26.37,...,93,20.37,208.8,133,9.40,10.6,4,2.86,0,False.
21,CO,77,408,393-7984,no,no,0,62.4,89,10.61,...,121,14.44,209.6,64,9.43,5.7,6,1.54,5,True.
22,AZ,130,415,358-1958,no,no,0,183.0,112,31.11,...,99,6.20,181.8,78,8.18,9.5,19,2.57,0,False.
23,SC,111,415,350-2565,no,no,0,110.4,103,18.77,...,102,11.67,189.6,105,8.53,7.7,6,2.08,2,False.
24,VA,132,510,343-4696,no,no,0,81.1,86,13.79,...,72,20.84,237.0,115,10.67,10.3,2,2.78,0,False.
25,NE,174,415,331-3698,no,no,0,124.3,76,21.13,...,112,23.55,250.7,115,11.28,15.5,5,4.19,3,False.
26,WY,57,408,357-3817,no,yes,39,213.0,115,36.21,...,112,16.24,182.7,115,8.22,9.5,3,2.57,0,False.
27,MT,54,408,418-6412,no,no,0,134.3,73,22.83,...,100,13.22,102.1,68,4.59,14.7,4,3.97,3,False.
28,MO,20,415,353-2630,no,no,0,190.0,109,32.30,...,84,21.95,181.5,102,8.17,6.3,6,1.70,0,False.
29,HI,49,510,410-7789,no,no,0,119.3,117,20.28,...,109,18.28,178.7,90,8.04,11.1,1,3.00,1,False.
30,IL,142,415,416-8428,no,no,0,84.8,95,14.42,...,63,11.62,250.5,148,11.27,14.2,6,3.83,2,False.
31,NH,75,510,370-3359,no,no,0,226.1,105,38.44,...,107,17.13,246.2,98,11.08,10.3,5,2.78,1,False.
32,LA,172,408,383-1121,no,no,0,212.0,121,36.04,...,115,2.65,293.3,78,13.20,12.6,10,3.40,3,False.
33,AZ,12,408,360-1596,no,no,0,249.6,118,42.43,...,119,21.45,280.2,90,12.61,11.8,3,3.19,1,True.
34,OK,57,408,395-2854,no,yes,25,176.8,94,30.06,...,75,16.58,213.5,116,9.61,8.3,4,2.24,0,False.

In [114]:
data[:8]

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False.
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False.
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False.
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False.
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False.
5,AL,118,510,391-8027,yes,no,0,223.4,98,37.98,...,101,18.75,203.9,118,9.18,6.3,6,1.70,0,False.
6,MA,121,510,355-9993,no,yes,24,218.2,88,37.09,...,108,29.62,212.6,118,9.57,7.5,7,2.03,3,False.
7,MO,147,415,329-9001,yes,no,0,157.0,79,26.69,...,94,8.76,211.8,96,9.53,7.1,6,1.92,0,False.

In [115]:
data[60:]

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
60,ID,174,408,359-5893,no,no,0,192.1,97,32.66,...,94,14.44,166.6,54,7.50,11.4,4,3.08,1,False.
61,CA,116,415,405-3371,no,yes,34,268.6,83,45.66,...,142,15.15,166.3,106,7.48,11.6,3,3.13,2,False.
62,MN,74,510,344-5117,no,yes,33,193.7,91,32.93,...,96,20.92,138.0,92,6.21,14.6,3,3.94,2,False.
63,SD,149,408,332-8160,no,yes,28,180.7,92,30.72,...,64,15.96,265.5,53,11.95,12.6,3,3.40,3,False.
64,NC,38,408,359-4081,no,no,0,131.2,98,22.30,...,97,13.85,159.0,106,7.15,8.2,6,2.21,2,False.
65,WA,40,415,352-8305,no,yes,41,148.1,74,25.18,...,88,14.41,214.1,102,9.63,6.2,5,1.67,2,False.
66,WY,43,415,329-9847,yes,no,0,251.5,105,42.76,...,104,18.09,157.8,67,7.10,9.3,4,2.51,0,False.
67,MN,113,408,365-9011,yes,no,0,125.2,93,21.28,...,119,17.54,129.3,139,5.82,8.3,8,2.24,0,False.
68,UT,126,408,338-9472,no,no,0,211.6,70,35.97,...,80,18.44,153.5,60,6.91,7.8,1,2.11,1,False.
69,TX,150,510,374-8042,no,no,0,178.9,101,30.41,...,110,14.37,148.6,100,6.69,13.8,3,3.73,4,True.
70,NJ,138,408,359-1231,no,no,0,241.8,93,41.11,...,83,14.49,295.3,104,13.29,11.8,7,3.19,3,False.
71,MN,162,510,413-7170,no,yes,46,224.9,97,38.23,...,84,16.00,254.6,61,11.46,12.1,2,3.27,0,False.
72,NM,147,510,415-2935,no,no,0,248.6,83,42.26,...,85,12.66,172.5,109,7.76,8.0,4,2.16,3,False.
73,NV,90,415,399-4246,no,no,0,203.4,146,34.58,...,117,19.27,152.4,105,6.86,7.3,4,1.97,1,False.
74,HI,85,415,362-5889,no,no,0,235.8,109,40.09,...,94,13.36,188.2,99,8.47,12.0,3,3.24,0,False.
75,MN,50,415,350-8921,no,no,0,157.1,90,26.71,...,72,18.98,181.4,111,8.16,6.1,2,1.65,1,False.
76,DC,82,415,374-5353,no,no,0,300.3,109,51.05,...,100,15.39,270.1,73,12.15,11.7,4,3.16,0,True.
77,NY,144,408,360-1171,no,no,0,61.6,117,10.47,...,85,6.55,173.0,99,7.79,8.2,7,2.21,4,True.
78,MN,46,415,355-8887,no,no,0,214.1,72,36.40,...,104,13.97,177.5,113,7.99,8.2,3,2.21,2,False.
79,MD,70,408,333-1967,no,no,0,170.2,98,28.93,...,102,13.19,228.6,76,10.29,15.0,2,4.05,1,False.
80,WV,144,415,354-4577,no,no,0,201.1,99,34.19,...,74,25.80,224.0,119,10.08,13.2,2,3.56,1,False.
81,OR,116,415,331-7425,yes,no,0,215.4,104,36.62,...,79,17.41,278.5,109,12.53,12.6,5,3.40,3,False.
82,CO,55,408,419-2637,no,yes,25,165.6,123,28.15,...,95,11.57,175.7,90,7.91,11.0,2,2.97,3,False.
83,GA,70,415,411-1530,no,yes,24,249.5,101,42.42,...,98,22.07,222.7,68,10.02,9.8,4,2.65,1,False.
84,TX,106,510,395-3026,no,no,0,210.6,96,35.80,...,85,21.18,191.4,88,8.61,12.4,1,3.35,2,True.
85,VT,128,510,388-6441,no,yes,29,179.3,104,30.48,...,86,19.20,323.0,78,14.54,8.6,7,2.32,0,False.
86,IN,94,408,402-1251,no,no,0,157.9,105,26.84,...,101,13.18,189.6,84,8.53,8.0,5,2.16,4,True.
87,WV,111,510,412-9997,no,no,0,214.3,118,36.43,...,76,17.72,182.4,98,8.21,12.0,2,3.24,1,False.
88,KY,74,415,346-7302,no,yes,35,154.1,104,26.20,...,84,10.49,202.1,57,9.09,10.9,9,2.94,2,False.
89,NJ,128,415,358-9095,no,no,0,237.9,125,40.44,...,93,21.05,208.9,68,9.40,13.9,4,3.75,1,True.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3303,WI,114,415,373-7308,no,yes,26,137.1,88,23.31,...,125,13.23,247.6,94,11.14,11.5,7,3.11,2,False.
3304,IL,71,510,330-7137,yes,no,0,186.1,114,31.64,...,140,16.88,206.5,80,9.29,13.8,5,3.73,4,True.
3305,IN,58,415,406-8445,no,yes,22,224.1,127,38.10,...,85,20.30,174.2,86,7.84,11.5,7,3.11,2,False.
3306,AL,106,408,404-5283,no,yes,29,83.6,131,14.21,...,131,17.33,229.5,73,10.33,8.1,3,2.19,1,False.
3307,OK,172,408,398-3632,no,no,0,203.9,109,34.66,...,123,19.89,160.7,65,7.23,17.8,4,4.81,4,False.
3308,IA,45,415,399-5763,no,no,0,211.3,87,35.92,...,97,14.08,265.9,72,11.97,13.3,6,3.59,1,False.
3309,VT,100,408,340-9449,yes,no,0,219.4,112,37.30,...,102,19.18,255.3,95,11.49,12.0,4,3.24,4,False.
3310,NY,94,415,363-1123,no,no,0,190.4,91,32.37,...,107,7.82,224.8,108,10.12,13.6,17,3.67,2,False.
3311,LA,128,415,361-2170,no,no,0,147.7,94,25.11,...,83,24.08,188.3,124,8.47,6.9,5,1.86,2,False.
3312,SC,181,408,406-6304,no,no,0,229.9,130,39.08,...,93,12.27,262.4,110,11.81,14.2,4,3.83,2,False.
3313,ID,127,408,392-5090,no,no,0,102.8,128,17.48,...,95,12.21,191.4,97,8.61,10.0,5,2.70,1,False.
3314,MO,89,415,373-7713,no,no,0,178.7,81,30.38,...,74,19.86,131.9,120,5.94,9.1,4,2.46,1,False.
3315,ME,149,415,392-1376,no,yes,18,148.5,106,25.25,...,106,9.73,178.3,98,8.02,6.5,4,1.76,0,False.
3316,MS,103,510,390-6388,no,yes,29,164.1,111,27.90,...,96,18.62,220.3,108,9.91,12.3,9,3.32,0,False.
3317,SD,163,415,379-7290,yes,no,0,197.2,90,33.52,...,113,16.02,211.1,94,9.50,7.8,8,2.11,1,False.
3318,OK,52,415,397-9928,no,no,0,124.9,131,21.23,...,118,25.54,192.5,106,8.66,11.6,4,3.13,2,False.
3319,WY,89,415,378-6924,no,no,0,115.4,99,19.62,...,115,17.84,280.9,112,12.64,15.9,6,4.29,3,False.
3320,GA,122,510,411-5677,yes,no,0,140.0,101,23.80,...,77,16.69,120.1,133,5.40,9.7,4,2.62,4,True.
3321,VT,60,415,400-2738,no,no,0,193.9,118,32.96,...,110,7.23,210.1,134,9.45,13.2,8,3.56,3,False.
3322,MD,62,408,409-1856,no,no,0,321.1,105,54.59,...,122,22.57,180.5,72,8.12,11.5,2,3.11,4,True.
3323,IN,117,415,362-5899,no,no,0,118.4,126,20.13,...,97,21.19,227.0,56,10.22,13.6,3,3.67,5,True.
3324,WV,159,415,377-1164,no,no,0,169.8,114,28.87,...,105,16.80,193.7,82,8.72,11.6,4,3.13,1,False.
3325,OH,78,408,368-8555,no,no,0,193.4,99,32.88,...,88,9.94,243.3,109,10.95,9.3,4,2.51,2,False.
3326,OH,96,415,347-6812,no,no,0,106.6,128,18.12,...,87,24.21,178.9,92,8.05,14.9,7,4.02,1,False.
3327,SC,79,415,348-3830,no,no,0,134.7,98,22.90,...,68,16.12,221.4,128,9.96,11.8,5,3.19,2,False.
3328,AZ,192,415,414-4276,no,yes,36,156.2,77,26.55,...,126,18.32,279.1,83,12.56,9.9,6,2.67,2,False.
3329,WV,68,415,370-3271,no,no,0,231.1,57,39.29,...,55,13.04,191.3,123,8.61,9.6,4,2.59,3,False.
3330,RI,28,510,328-8230,no,no,0,180.8,109,30.74,...,58,24.55,191.9,91,8.64,14.1,6,3.81,2,False.
3331,CT,184,510,364-6381,yes,no,0,213.8,105,36.35,...,84,13.57,139.2,137,6.26,5.0,10,1.35,2,False.
3332,TN,74,415,400-4344,no,yes,25,234.4,113,39.85,...,82,22.60,241.4,77,10.86,13.7,4,3.70,0,False.

In [116]:
data[3320:]

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
3320,GA,122,510,411-5677,yes,no,0,140.0,101,23.80,...,77,16.69,120.1,133,5.40,9.7,4,2.62,4,True.
3321,VT,60,415,400-2738,no,no,0,193.9,118,32.96,...,110,7.23,210.1,134,9.45,13.2,8,3.56,3,False.
3322,MD,62,408,409-1856,no,no,0,321.1,105,54.59,...,122,22.57,180.5,72,8.12,11.5,2,3.11,4,True.
3323,IN,117,415,362-5899,no,no,0,118.4,126,20.13,...,97,21.19,227.0,56,10.22,13.6,3,3.67,5,True.
3324,WV,159,415,377-1164,no,no,0,169.8,114,28.87,...,105,16.80,193.7,82,8.72,11.6,4,3.13,1,False.
3325,OH,78,408,368-8555,no,no,0,193.4,99,32.88,...,88,9.94,243.3,109,10.95,9.3,4,2.51,2,False.
3326,OH,96,415,347-6812,no,no,0,106.6,128,18.12,...,87,24.21,178.9,92,8.05,14.9,7,4.02,1,False.
3327,SC,79,415,348-3830,no,no,0,134.7,98,22.90,...,68,16.12,221.4,128,9.96,11.8,5,3.19,2,False.
3328,AZ,192,415,414-4276,no,yes,36,156.2,77,26.55,...,126,18.32,279.1,83,12.56,9.9,6,2.67,2,False.
3329,WV,68,415,370-3271,no,no,0,231.1,57,39.29,...,55,13.04,191.3,123,8.61,9.6,4,2.59,3,False.
3330,RI,28,510,328-8230,no,no,0,180.8,109,30.74,...,58,24.55,191.9,91,8.64,14.1,6,3.81,2,False.
3331,CT,184,510,364-6381,yes,no,0,213.8,105,36.35,...,84,13.57,139.2,137,6.26,5.0,10,1.35,2,False.
3332,TN,74,415,400-4344,no,yes,25,234.4,113,39.85,...,82,22.60,241.4,77,10.86,13.7,4,3.70,0,False.

In [117]:
## Usuarios con Total Mins > 300
data1 = data[data["Day Mins"]>300]
data1.shape

(43, 21)

In [118]:
## Usuarios de Nueva York [State == "NY"]
data2 = data[data["State"]=="NY"]
data2.shape

(83, 21)

In [119]:
## 
data3 = data[(data["Day Mins"]>300) & (data["State"]=="NY")]
data3.shape

(2, 21)

In [120]:
data4 = data[(data["Day Mins"]>300) | (data["State"]=="NY")]
data4.shape

(124, 21)

In [121]:
data5 = data[data["Day Calls"]<data["Night Calls"]]
data5.shape

(1626, 21)

In [122]:
data6 = data[data["Day Mins"]<data["Night Mins"]]
data6.shape

(2051, 21)

In [123]:
##Minutos de día, de noche y Longitud de la Cuenta de los promeros 50 individuos
subset_first_50 = data[['Day Mins', 'Night Mins', "Account Length"]][:50]
subset_first_50.shape

(50, 3)

In [124]:
data.ix[:10, 3:6] # Primeras 10 fila, columnas 3 a la 6

D:\Programas_win\anac\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.

       Phone Int'l Plan VMail Plan
0   382-4657         no        yes
1   371-7191         no        yes
2   358-1921         no         no
3   375-9999        yes         no
4   330-6626        yes         no
5   391-8027        yes         no
6   355-9993         no        yes
7   329-9001        yes         no
8   335-4719         no         no
9   330-8173        yes        yes
10  329-6603         no         no

In [125]:
data.iloc[:10,3:6]

      Phone Int'l Plan VMail Plan
0  382-4657         no        yes
1  371-7191         no        yes
2  358-1921         no         no
3  375-9999        yes         no
4  330-6626        yes         no
5  391-8027        yes         no
6  355-9993         no        yes
7  329-9001        yes         no
8  335-4719         no         no
9  330-8173        yes        yes

In [126]:
data.iloc[:, 3:6].shape

(3333, 3)

In [127]:
data.loc[ [1, 5, 8, 36], ["Area Code", "VMail Plan", "Day Mins"]]

    Area Code VMail Plan  Day Mins
1         415        yes     161.6
5         510         no     223.4
8         408         no     184.5
36        408        yes     146.3

In [128]:
data["Total Mins"] = data["Day Mins"] + data["Eve Mins"] + data["Night Mins"]

In [129]:
data.head()

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?,Total Mins
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,16.78,244.7,91,11.01,10.0,3,2.70,1,False.,707.2
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,16.62,254.4,103,11.45,13.7,3,3.70,1,False.,611.5
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,10.30,162.6,104,7.32,12.2,5,3.29,0,False.,527.2
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,5.26,196.9,89,8.86,6.6,7,1.78,2,False.,558.2
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,12.61,186.9,121,8.41,10.1,3,2.73,3,False.,501.9

In [130]:
data["Total Calls"] = data["Day Calls"] + data["Eve Calls"] + data["Night Calls"]

In [131]:
data.head()

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?,Total Mins,Total Calls
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,244.7,91,11.01,10.0,3,2.70,1,False.,707.2,300
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,254.4,103,11.45,13.7,3,3.70,1,False.,611.5,329
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,162.6,104,7.32,12.2,5,3.29,0,False.,527.2,328
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,196.9,89,8.86,6.6,7,1.78,2,False.,558.2,248
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,186.9,121,8.41,10.1,3,2.73,3,False.,501.9,356

In [132]:
data.shape

(3333, 23)

## Generación aleatoria de número

In [133]:
 import numpy as np

In [134]:
#Generar un número aleatorio entero entre 1 y 100
np.random.randint(1,100)

65

In [135]:
#Genera valores entre 0 y 1
np.random.random()

0.4762251424146674

In [136]:
def randint_list(n, a, b):
    x=[]
    for i in range(n):
        x.append(np.random.randint(a, b))
        
    return x

In [137]:
randint_list(25, 1, 50)

[36,
 6,
 33,
 5,
 33,
 36,
 16,
 17,
 22,
 33,
 25,
 36,
 15,
 26,
 46,
 4,
 46,
 38,
 12,
 32,
 40,
 6,
 3,
 35,
 36]

In [138]:
import random

In [139]:
#Genero valores entre 0 y 100 que son multiplos de 7
random.randrange(0, 100, 7)

35

#### Shuffling

In [140]:
a = np.arange(0, 100)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [141]:
np.random.shuffle(a)
a

array([88,  4, 68, 85, 29, 31, 54, 22, 83, 65, 30, 84, 69, 87,  9, 21, 91,
        8, 72, 49, 18, 77, 32, 64,  1, 50, 13,  2,  3, 25,  7, 43, 20, 60,
       76, 90,  5, 28, 75, 94, 44, 27, 17, 53, 81, 96, 92, 23, 48, 47, 24,
       57, 38, 71, 63, 89, 55, 59, 15, 58, 82, 62, 16, 98, 74, 67, 14, 37,
       12, 70, 35, 97, 95, 86, 34, 52, 93, 36, 80, 45, 56, 10, 11, 26, 73,
       51,  6, 42, 39, 99, 46, 61, 66, 41,  0, 40, 79, 19, 78, 33])

In [142]:
data.head()

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?,Total Mins,Total Calls
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,244.7,91,11.01,10.0,3,2.70,1,False.,707.2,300
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,254.4,103,11.45,13.7,3,3.70,1,False.,611.5,329
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,162.6,104,7.32,12.2,5,3.29,0,False.,527.2,328
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,196.9,89,8.86,6.6,7,1.78,2,False.,558.2,248
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,186.9,121,8.41,10.1,3,2.73,3,False.,501.9,356

In [143]:
data.shape

(3333, 23)

In [145]:
column_list =  data.columns.tolist()
column_list

['State',
 'Account Length',
 'Area Code',
 'Phone',
 "Int'l Plan",
 'VMail Plan',
 'VMail Message',
 'Day Mins',
 'Day Calls',
 'Day Charge',
 'Eve Mins',
 'Eve Calls',
 'Eve Charge',
 'Night Mins',
 'Night Calls',
 'Night Charge',
 'Intl Mins',
 'Intl Calls',
 'Intl Charge',
 'CustServ Calls',
 'Churn?',
 'Total Mins',
 'Total Calls']

In [154]:
np.random.choice(column_list)

'Day Mins'

#### Seed

In [155]:
np.random.seed(2018)

In [156]:
for i in range(5):
    print(np.random.random())

0.8823493117539459
0.10432773786047767
0.9070093335163405
0.3063988986063515
0.446408872427422